# User Config
# ===========
# fill/change these fields to match your own.

# Identity
# --------

title:       Polar
description: White-Clean Jekyll Theme

logo:  "/assets/img/north-pole.png"
cover: "/assets/img/tired-bear.png"

baseurl: "/polar"
url:     "https://neizod.github.io"

owner:  polarbear
rights: All Right Reserved


# Social & Sharing
# ----------------

google:
  analytics:
  verification:

facebook:
  username:
  app_id:

twitter:
  username:
  large_img: sometimes

disqus:
  username:


# Content Format
# --------------

timezone: Asia/Bangkok
mathjax:  true



# ----------------------------------------------------------------------------

# Engine Config
# =============
# you shouldn't change this unless you really know what you're doing.

theme: jekyll-theme-polar

permalink: date

collections:
  projects:
    output: true
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: docs
    values:
      layout: doc

pagination:
  enabled: true
  per_page: 10
  sort_reverse: true
  permalink: /page:num.html

sass:
  sass_dir: "_sass/"
  style: compressed

exclude:
  - README.md
  - LICENSE.md
  - CONTRIBUTING.md

plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2

empty_array: []
